# Generated by Django 3.1.3 on 2020-11-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_blogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='pat_name',
        ),
    ]
